"""Toolbar icons for TabIt Py.

Each icon is a 16x16 pixel grid expressed as 16 strings of 16 characters;
characters map to colors via ``PAL``. ``'.'`` is the toolbar face color so
icons blend into the classic gray buttons. Icons are built lazily into
tkinter PhotoImages (a Tk root must exist first).
"""

FACE = "#c0c0c0"

PAL = {
    ".": FACE,
    "k": "#000000",   # black outline
    "w": "#ffffff",   # white / paper
    "d": "#808080",   # mid gray
    "b": "#000080",   # navy (arrows)
    "y": "#ffd84a",   # folder light
    "Y": "#c8990a",   # folder dark
    "c": "#39518c",   # floppy body
    "l": "#7c93c4",   # floppy light
    "r": "#c00000",   # red (stop / cut handle)
    "g": "#108010",   # green (play / cut handle)
    "s": "#b0b0b0",   # silver (floppy shutter)
}

_RAW = {
    "new": [
        "................",
        "...kkkkkkkk.....",
        "...kwwwwwkkk....",
        "...kwwwwwkwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kwwwwwwwk....",
        "...kkkkkkkkk....",
        "................",
        "................",
    ],
    "open": [
        "................",
        "................",
        "..kkkk..........",
        ".kyyyyk.........",
        "kyyyyyykkkkkk...",
        "kyyyyyyyyyyyk...",
        "kyyyyyyyyyyyk...",
        "kYYYYYYYYYYYk...",
        "kYYYYYYYYYYYk...",
        "kYYYYYYYYYYYk...",
        "kYYYYYYYYYYYk...",
        "kkkkkkkkkkkkk...",
        "................",
        "................",
        "................",
        "................",
    ],
    "save": [
        "................",
        ".kkkkkkkkkkkk...",
        ".kccccccccccsk..",
        ".kcssssssscsk...",
        ".kcssssssscsk...",
        ".kcccccccccsk...",
        ".kcccccccccck...",
        ".kcwwwwwwwwck...",
        ".kcwkkkkkkwck...",
        ".kcwkkkkkkwck...",
        ".kcwkkkkkkwck...",
        ".kcwwwwwwwwck...",
        ".kkkkkkkkkkkk...",
        "................",
        "................",
        "................",
    ],
    "cut": [
        "................",
        "..k.......k.....",
        "..kk.....kk.....",
        "...kk...kk......",
        "....kk.kk.......",
        ".....kkk........",
        "......k.........",
        ".....kkk........",
        "....kk.kk.......",
        "...rk...gk......",
        "..rrk...gck.....",
        "..rrk...gck.....",
        "...rk...gk......",
        "....kkkkk.......",
        "................",
        "................",
    ],
    "copy": [
        "................",
        ".....kkkkkk.....",
        ".....kwwwwk.....",
        "...kkkkkwwk.....",
        "...kwwwkwwk.....",
        "...kwwwkkkk.....",
        "...kwwwwwwk.....",
        "...kwwwwwwk.....",
        "...kwwwwwwk.....",
        "...kwwwwwwk.....",
        "...kwwwwwwk.....",
        "...kwwwwwwk.....",
        "...kkkkkkkk.....",
        "................",
        "................",
        "................",
    ],
    "paste": [
        "................",
        ".....kkk........",
        "....kwwwk.......",
        "..kkkkkkkkk.....",
        "..kdddddddk.....",
        "..kdkkkkkdk.....",
        "..kdwwwwwwk.....",
        "..kdwwwwwwk.....",
        "..kdwwwwwwk.....",
        "..kdwwwwwwk.....",
        "..kdwwwwwwk.....",
        "..kdwwwwwwk.....",
        "..kddddddddk....",
        "..kkkkkkkkkk....",
        "................",
        "................",
    ],
    "undo": [
        "................",
        "................",
        "....b...........",
        "...bb...........",
        "..bbbbbb........",
        ".bbbbbbbbb......",
        "..bb...bbbbb....",
        "...b.....bbb....",
        ".........bbb....",
        "........bbb.....",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "redo": [
        "................",
        "................",
        "...........b....",
        "...........bb...",
        "........bbbbbb..",
        "......bbbbbbbbb.",
        "....bbbbb...bb..",
        "....bbb.....b...",
        "....bbb.........",
        ".....bbb........",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "play": [
        "................",
        "................",
        "....g...........",
        "....gg..........",
        "....ggg.........",
        "....gggg........",
        "....ggggg.......",
        "....gggggg......",
        "....ggggggg.....",
        "....gggggg......",
        "....ggggg.......",
        "....gggg........",
        "....ggg.........",
        "....gg..........",
        "....g...........",
        "................",
    ],
    "playcur": [
        "................",
        "................",
        ".kk.g...........",
        ".kk.gg..........",
        ".kk.ggg.........",
        ".kk.gggg........",
        ".kk.ggggg.......",
        ".kk.gggggg......",
        ".kk.ggggggg.....",
        ".kk.gggggg......",
        ".kk.ggggg.......",
        ".kk.gggg........",
        ".kk.ggg.........",
        ".kk.gg..........",
        ".kk.g...........",
        "................",
    ],
    "stop": [
        "................",
        "................",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "...rrrrrrrrr....",
        "................",
        "................",
        "................",
        "................",
    ],
    "loop": [
        "................",
        "....kkkkkk......",
        "...kk....kk.....",
        "..kk......kk....",
        ".bk........kb...",
        "bbbk......kbbb..",
        ".bbk......kbb...",
        "..bk......kb....",
        "..kk......kk....",
        "...kk....kk.....",
        "....kkkkkk......",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    "metro": [
        "................",
        ".......k........",
        "......kdk.......",
        "......ddk.......",
        ".....dddk.......",
        ".....dddkk......",
        "....ddddkk......",
        "....dddddk......",
        "...ddddddk......",
        "...ddddddk......",
        "..dddddddk......",
        "..kkkkkkkkk.....",
        ".kkkkkkkkkkk....",
        "................",
        "................",
        "................",
    ],
}

_cache = {}


def get(name):
    """Return a cached PhotoImage for the named icon (Tk root required)."""
    if name not in _cache:
        import tkinter as tk
        rows = _RAW[name]
        img = tk.PhotoImage(width=len(rows[0]), height=len(rows))
        for y, row in enumerate(rows):
            img.put("{" + " ".join(PAL[ch] for ch in row) + "}", to=(0, y))
        _cache[name] = img
    return _cache[name]
